
spring:
  redis:
    database: 0
    expire: 1800
    host: localhost
    password: ''
    pool:
      max:
        active: 8
        idle: 8
        wait: -1
      min:
        idle: 0
    port: 6379
    timeout: 5000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1765000
      maximum-pool-size: 15
      minimum-idle: 10
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mediocre_blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

logging:
  config: classpath:logback-spring.xml

app:
  interface-log: true